apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podinfo-pr-envs
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - pullRequest:
        github:
          owner: dana951
          repo: gitops-manifests
          appSecretName: gitops-manifests-github-app
        requeueAfterSeconds: 120 # Polls every 2 minutes
        filters:
          - branchMatch: "^pr-[0-9]+-[a-f0-9]{7}$"
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: "{{ .branch }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/dana951/gitops-manifests.git
        targetRevision: "{{ .branch }}"
        path: charts/podinfo
        helm:
          releaseName: "{{ .branch }}"
          valueFiles:
            - "../../environments/podinfo/{{ .branch }}/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .branch }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
